/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cz.honzovysachy;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bd=0x7f020000;
        public static final int bj=0x7f020001;
        public static final int bk=0x7f020002;
        public static final int bp=0x7f020003;
        public static final int bs=0x7f020004;
        public static final int bv=0x7f020005;
        public static final int cd=0x7f020006;
        public static final int cj=0x7f020007;
        public static final int ck=0x7f020008;
        public static final int cp=0x7f020009;
        public static final int cs=0x7f02000a;
        public static final int cv=0x7f02000b;
        public static final int icon=0x7f02000c;
    }
    public static final class id {
        public static final int black=0x7f050006;
        public static final int blackelo=0x7f050014;
        public static final int blackelostatic=0x7f050013;
        public static final int blackstatic=0x7f050005;
        public static final int date=0x7f05000e;
        public static final int datestatic=0x7f05000d;
        public static final int event=0x7f05000a;
        public static final int eventstatic=0x7f050009;
        public static final int filename=0x7f050001;
        public static final int filenamestatic=0x7f050000;
        public static final int result=0x7f050008;
        public static final int resultstatic=0x7f050007;
        public static final int round=0x7f050010;
        public static final int roundstatic=0x7f05000f;
        public static final int save=0x7f050002;
        public static final int site=0x7f05000c;
        public static final int sitestatic=0x7f05000b;
        public static final int white=0x7f050004;
        public static final int whiteelo=0x7f050012;
        public static final int whiteelostatic=0x7f050011;
        public static final int whitestatic=0x7f050003;
    }
    public static final class layout {
        public static final int pgn_header=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
